version: '3.3'

services:
  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1q2w3e4r
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb/mariadb.cnf:/etc/mysql/conf.d/mariadb.cnf
      - ./mariadb/001init-db.sql:/docker-entrypoint-initdb.d/001init-db.sql
      - ./mariadb/002init-data.sql:/docker-entrypoint-initdb.d/002init-data.sql
      - ./mariadb/003init-user.sql:/docker-entrypoint-initdb.d/003init-user.sql
      - ./mariadb/004init-procedures.sql:/docker-entrypoint-initdb.d/004init-procedures.sql
      - ./mariadb/data:/var/lib/mysql
    networks:
      - app-network

  centos-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: centos-server
    restart: always
    tty: true
    stdin_open: true
    volumes:
      - centos-server-data:/srv/data
    depends_on:
      - mariadb
    networks:
      - app-network
    ports:
      - "2222:22"
      - "3334:3334"

volumes:
  centos-server-data:

networks:
  app-network:
    driver: bridge
